version: 2
updates:
  - package-ecosystem: "pip"
    commit-message:
      include: "scope"
      prefix: "requirements"
    directory: "/"
    labels:
      - "dependencies"
      - "enhancement"
    schedule:
      interval: "daily"
