name: Detect .dockerignore out-of-sync with git ls-files

on:
  pull_request:
  push:
  schedule:
    - cron: '0 16 * * 5'  # Every Friday 4pm
  workflow_dispatch:

jobs:
  dockerignore_detect_out_of_sync:
    name: Detect .dockerignore out-of-sync with git ls-files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Check for out-of-sync .dockerignore
        run: |-
          diff -U0 <(./generate_whitelist_dockerignore_file.sh) .dockerignore
